name: Build Caddy with naive

on:
  push:
    branches:
      - naive

jobs:
  build_caddy_with_naive:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1
      - name: Install xcaddy 
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - name: Build caddy
        run: ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive 
      - name: Check files
        run: file ./caddy
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: ./caddy
          asset_name: caddy-naive-linux-amd64
#          tag: ${{  }}
#          overwrite: true
          body: "This is my release text"


