name: Build Caddy with naive

on:
  push:
    branches:
      - naive

jobs:
  build_caddy_with_naive:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1
      - name: Initialization environment
        run: apt install -y ca-certificates openssl
      - name: Install xcaddy 
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - name: Build caddy
        run: ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
      - name: echo eval
        run: echo ${GITHUB_WORKSPACE}


